[package]
name = "xcp_idl_generator_derive"
version = "0.3.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0", features = ["full"] }
#syn = { version = "2.0", features = ["full"] }

quote = "1.0"
lazy_static = "1.4"