[package]
name = "single_thread_demo"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
log = "0.4.21"
env_logger = "0.11.3"
lazy_static = "1.4.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

xcp = { path = "../../", features = [] }