[package]
name = "xcp_idl_generator"
version = "0.3.0"
edition = "2024"

[dependencies]
ctor = "0.2.8"
#ctor = "0.4"
lazy_static = "1.4"
regex = "1.10.6"
xcp_idl_generator_derive = { path = "./xcp_idl_generator_derive/" }

[lib]
path = "src/lib.rs"
