/* automatically generated by rust-bindgen 0.69.4 */

extern "C" {
    pub fn mdfOpen(filename: *const ::std::os::raw::c_char) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn mdfCreateChannelGroup(recordId: u32, recordLen: u32, timeChannelSize: u32, timeChannelConv: f64) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn mdfCreateChannel(
        name: *const ::std::os::raw::c_char,
        msize: u8,
        encoding: i8,
        dim: u32,
        byteOffset: u32,
        factor: f64,
        offset: f64,
        unit: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn mdfWriteHeader() -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn mdfWriteRecord(record: *const u8, recordLen: u32) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn mdfClose() -> ::std::os::raw::c_int;
}
